# Generated by Django 6.0.5 on 2026-05-29 17:37

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100)),
                ('service', models.CharField(choices=[('impression', 'Impression'), ('inscription', 'Inscription'), ('photo', 'Photo minute'), ('carnet', 'Carnet'), ('autre', 'Autre')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('prix_unitaire', models.IntegerField(default=0)),
                ('quantite', models.IntegerField(default=1)),
                ('montant', models.IntegerField(default=0)),
                ('depense', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.date.today)),
                ('heure', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('montant', models.IntegerField()),
                ('motif', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
