# Generated by Django 6.0.5 on 2026-05-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('mobile_money', models.IntegerField(default=0)),
                ('especes', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='activite',
            name='service',
            field=models.CharField(choices=[('impression', 'Impression'), ('photocopie_bn', 'Photocopie Blanc/Noir'), ('photocopie_couleur', 'Photocopie Couleur'), ('inscription', 'Inscription'), ('traitement_texte', 'Traitement de texte'), ('creation_cv', 'Création CV'), ('lettre_motivation', 'Lettre de motivation'), ('convocation', 'Impression convocation'), ('paiement', 'Paiement'), ('confection_document', 'Confection document'), ('modification_document', 'Modification document'), ('photo_minute', 'Photo minute'), ('envoi_document', 'Envoi document'), ('carte_pvc', 'Carte PVC'), ('carnet', 'Carnet'), ('autre', 'Autre')], max_length=50),
        ),
    ]
