# Generated by Django 6.0.5 on 2026-05-19 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100)),
                ('service', models.CharField(choices=[('impression', 'Impression'), ('inscription', 'Inscription'), ('photo', 'Photo minute'), ('carnet', 'Carnet'), ('autre', 'Autre')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('montant', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('heure', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='session',
            name='client',
        ),
        migrations.RemoveField(
            model_name='session',
            name='ordinateur',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Ordinateur',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
