# Generated by Django 6.0.5 on 2026-05-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_paiementjour_alter_activite_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='mode_paiement',
            field=models.CharField(choices=[('mobile', 'Mobile Money'), ('espece', 'Espèce')], default='espece', max_length=20),
        ),
    ]
