# Generated by Django 6.0.5 on 2026-05-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_activite_remove_session_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='depense',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activite',
            name='prix_unitaire',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activite',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
    ]
