# Generated by Django 6.0.5 on 2026-06-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_activite_mode_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='client',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
