# Generated by Django 6.0.5 on 2026-06-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_activite_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='mode_paiement',
            field=models.CharField(choices=[('mobile_money', 'Mobile Money'), ('especes', 'Espèces')], default='especes', max_length=20),
        ),
    ]
