# Generated by Django 6.0.5 on 2026-06-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_create_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='motif',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
